- name: create dork user
  user:
    name: "{{ dork_user }}"

- name: add dork user to sudoers
  lineinfile:
    line: "{{ dork_user }}    ALL=(ALL)   NOPASSWD: ALL"
    dest: /etc/sudoers

- name: enable ttys
  lineinfile:
    line: "Defaults !requiretty"
    regexp: "Defaults requiretty"
    dest: /etc/sudoers

# ======================================================================
# Copy ssh configuration file
# ======================================================================
- name: create ssh config directory
  file:
    path: /home/{{ dork_user }}/.ssh
    state: directory
    owner: "{{ dork_user }}"
- name: copy ssh configuration
  copy:
    src: ssh-config
    dest: /home/{{ dork_user }}/.ssh/config
